apiVersion: "v1"
kind: "Service"
metadata:
  name: "rag-api-service"
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  namespace: "default"
  labels:
    k8s-app: "rag-api"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    k8s-app: "rag-api"
  type: "LoadBalancer"
  loadBalancerIP: ""