apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  labels:
    k8s-app: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rag-api
  template:
    metadata:
      labels:
        k8s-app: rag-api
    spec:
      serviceAccountName: k8s-service-account
      containers:
      - name: rag-api
        image: us-central1-docker.pkg.dev/sab-llm-hack-sbx-6315/gcf-artifacts/ragpipeline:v1
        imagePullPolicy: Always
        env:
        - name: FLASK_APP
          value: "main.py"
        - name: REDIS_SERVER
          value: "celery-redis:6379/0"
        - name: PDF_BATCH_SIZE
          value: "10"
        - name: GCS_BUCKET
          value: "synxis-src"
        - name: VECTOR_HOST
          value: "127.0.0.1"
        - name: VECTOR_PORT
          value: "5432"
        - name: VECTOR_USER
          value: "postgres"
        - name: VECTOR_PWD
          value: "SynXisSearchTest9"
        - name: VECTOR_DB
          value: "synxisdb"
        - name: VECTOR_COLLECTIONS
          value: "sabre_vector_synxis"
        command: ["flask"]
        args: ["run", "--host=0.0.0.0"]
        ports:
        - containerPort: 5000
          name: rag-api
          protocol: TCP

