wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707162497.252438
    t:
      1:
      - 5
      - 53
      - 55
      - 87
      - 95
      2:
      - 1
      - 5
      - 53
      - 55
      - 86
      - 87
      - 95
      3:
      - 23
      4: 3.10.10
      5: 0.16.2
      8:
      - 4
      - 5
      9:
        2: llama_index
      13: darwin-arm64
