apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-worker-dataprocessing
  labels:
    k8s-app: rag-worker-dataprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rag-worker-dataprocessing
  template:
    metadata:
      labels:
        k8s-app: rag-worker-dataprocessing
    spec:
      serviceAccountName: k8s-service-account
      containers:
      - name: worker-data-extraction
        image: us-central1-docker.pkg.dev/sab-llm-hack-sbx-6315/gcf-artifacts/ragpipeline:v1
        imagePullPolicy: Always
        env:
        - name: REDIS_SERVER
          value: "celery-redis:6379/0"
        - name: PDF_BATCH_SIZE
          value: "25"
        - name: GCS_BUCKET
          value: "synxis-src"
        - name: VECTOR_HOST
          value: "127.0.0.1"
        - name: VECTOR_PORT
          value: "5432"
        - name: VECTOR_USER
          valueFrom:
            secretKeyRef:
              name: pgvector-store-secrets
              key: VECTOR_USER
        - name: VECTOR_PWD
          valueFrom:
            secretKeyRef:
              name: pgvector-store-secrets
              key: VECTOR_PWD
        - name: VECTOR_DB
          valueFrom:
            secretKeyRef:
                name: pgvector-store-secrets
                key: VECTOR_DB
        - name: VECTOR_COLLECTIONS
          value: "sabre_vector_synxis"
        - name: NFS_MOUNT
          value: "/sharedvol1"
        volumeMounts:
          - name: fileserver
            mountPath: /sharedvol1 # the shared directory
        command: ["celery"]
        args: ["-A", "tasks", "worker", "--concurrency=10","--pool=gevent","--queues=data_processing","--loglevel=debug" , "-E"]
        resources:
          limits:
            cpu: 6.0
            memory: 8096Mi
          requests:
             cpu: 4.0
             memory: 4096Mi
      volumes:
        - name: fileserver
          persistentVolumeClaim:
            claimName: fileserver1
      nodeSelector:
        #<labelname>:value
        cloud.google.com/gke-nodepool: ragpool